version: '3'

services:
  db:
    build: ./database/
    env_file:
      - ./database/.env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
  
  mlflow:
    build: ./mlflow/
    env_file:
      - ./mlflow/.env
      - ./database/.env
    depends_on:
      - db
    ports:
      - '4444:5000'
    restart: always
    links:
      - "db:mlflow-db"