trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: KubeflowUploadPipeline@0
  inputs:
    kubeflowEndpoint: 'http://cz-prgdas083.cee.ema.ad.pwcinternal.com:30001'
    pipelineFilePath: 'hello_kf.tar.gz'