trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pip install kfp'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'dsl-compile --py hello_kf.py --output hello_kf.tar.gz'
    
- task: KubeflowUploadPipeline@0
  inputs:
    kubeflowEndpoint: '$(host)'
    bearerToken: '$(token)'
    kubeflowPipelineTask: 'uploadNew'
    pipelineFilePath: 'hello_kf.tar.gz'
    newPipelineName: 'Hello_Kubeflow'
    newPipelineDescription: 'Pipeline description'