apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: rzydyk001
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifact-store
  namespace: rzydyk001
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi

