apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: rzydyk001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-db
  template:
    metadata:
      labels:
        app: mlflow-db
    spec:
      containers:
      - name: mlflow-db
        image: acrname.azurecr.io/kubeflow/mlflow-db:latest
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
          subPath: pg-data
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: postgre
          protocol: TCP
        envFrom:
          - secretRef:
              name: db-creds
          - configMapRef:
              name: db-config
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data