apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: rzydyk001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: acrname.azurecr.io/kubeflow/mlflow:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1Gi"
        volumeMounts:
        - mountPath: /home
          name: artifact-store
          subPath: .
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: db-creds
        - secretRef:
            name: azure-creds
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: artifact-store
        persistentVolumeClaim:
          claimName: artifact-store