apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  labels:
    name: pv-prometheus
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /NFS-SHARE/kubeflow/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - some.server.com

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-test-server
  labels:
    pv: pv-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  selector:
    matchLabels:
      name: pv-prometheus