apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jupyter
  labels:
    name: pv-jupyter
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /NFS-SHARE/kubeflow/jupyter
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - some.server.com

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pv: pv-jupyter
  name: workspace-jupytertest
  namespace: kubeflow-user-example-com
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      name: pv-jupyter