apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-data
  labels:
    name: pv-db-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /NFS-SHARE/kubeflow/mlflow-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - some.server.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-artifact-store
  labels:
    name: pv-artifact-store
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /NFS-SHARE/kubeflow/artifacts
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - some.server.com

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: rzydyk001
  labels:
    pv: d
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      name: pv-db-data
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifact-store
  namespace: rzydyk001
  labels:
    pv: pv-artifact-store
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      name: pv-artifact-store
  resources:
    requests:
      storage: 5Gi

